import type { IControls } from '../controls.i';

export const ZHCNCONTROLS: IControls = {
  accessControl: '权限设置 ',
  add: '添加',
  address: '地址',
  birthday: '出生日期',
  cancel: '取消',
  cellphone: '手机号',
  checkAll: '全选',
  city: '市',
  confirm: '确定',
  delete: '删除',
  department: '部门',
  description: '描述',
  edit: '编辑',
  email: '邮箱',
  fullName: '名字全称',
  home: '首页',
  keyword: '关键字',
  name: '名称',
  new: '新增',
  newPassword: '新密码',
  login: '登录',
  loginName: '登录名',
  logout: '退出',
  ok: '确定',
  order: '排序',
  originalPassword: '旧密码',
  operation: '操作',
  password: '密码',
  passwordConfirm: '密码确认',
  province: '省',
  reset: '重置',
  resetPassword: '密码重置',
  remark: '备注',
  role: '角色',
  roles: '角色',
  roleUsers: '角色用户',
  town: '区县',
  save: '保存',
  search: '查询',
  settings: '设置',
  statistics: '统计',
  uncheckAll: '全不选',
  userName: '用户名',
  userProfile: '用户信息',
  userRoles: '用户角色',
  languages: [
    { name: 'zh-cn', text: '中文' },
    { name: 'en-us', text: 'English' }
  ]
};
