import type { IControls } from '../controls.i';

export const ENUSCONTROLS: IControls = {
  accessControl: 'Access control',
  add: 'Add',
  address: 'Address',
  birthday: 'Birthday',
  cancel: 'Cancel',
  cellphone: 'Cellphone',
  checkAll: 'Check all',
  city: 'City',
  close: 'Close',
  confirm: 'Confirm',
  delete: 'Delete',
  department: 'Department',
  description: 'Description',
  edit: 'Edit',
  email: 'Email',
  fullName: 'Full name',
  home: 'Home',
  keyword: 'Keyword',
  login: 'Login',
  loginName: 'Login name',
  logout: 'Logout',
  name: 'Name',
  new: 'New',
  newPassword: 'New password',
  order: 'Order',
  originalPassword: 'Original password',
  ok: 'Ok',
  operation: 'Operation',
  password: 'Password',
  passwordConfirm: 'Password confirm',
  province: 'Province',
  remark: 'Remark',
  reset: 'Reset',
  resetPassword: 'Reset password',
  role: 'Role',
  roles: 'Roles',
  roleUsers: 'Role users',
  save: 'Save',
  search: 'Search',
  settings: 'Settings',
  statistics: 'Statistics',
  town: 'Town',
  uncheckAll: 'Uncheck all',
  userName: 'Login name',
  userProfile: 'User profile',
  userRoles: 'User roles',
  languages: [
    { name: 'zh-cn', text: '中文'},
    { name: 'en-us', text: 'English'}
  ]
};
