# It will be triggered when front-end/react related files changed.
# It runs eslint, unit tests and e2e tests(to do).

name: 'React PR checks'

on:
  pull_request:
    branches:
      - 'main'
      - 'releases/**'
    paths:
      - 'front-end/react/**/*'
      - '.github/workflows/react-pr-checks.yml'
  workflow_dispatch:

permissions: write-all

defaults:
  run:
    working-directory: ./front-end/react

jobs:
  react_lint_unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2.2.1
        id: changes
        with:
          filters: |
            ui:
              - 'front-end/react/**/*'
              - 'my-notes/packages/shared/**/*'
              - '.github/workflows/react-pr-checks.yml'

      - if: steps.changes.outputs.ui == 'true'
        name: Checkout
        uses: actions/checkout@v3

      - if: steps.changes.outputs.ui == 'true'
        uses: ./.github/actions/use-node
        with:
          yarn-lock-path: front-end/react/yarn-lock.json

      - if: steps.changes.outputs.ui == 'true'
        name: Install packages
        run: |
          yarn

      - if: steps.changes.outputs.ui == 'true'
        name: Run lint
        run: |
          yarn lint

      - if: steps.changes.outputs.ui == 'true'
        name: Run build
        run: |
          yarn build
  